# 1. Import Dependencies

In [29]:
#Install SWIG https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip/download?use_mirror=ixpeering

In [30]:
!pip install gym[box2d] pyglet==1.3.2

In [31]:
!pip install stable_baselines3[extra]

In [32]:
import gym 
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import os

# 2. Test Environment

In [39]:
environment_name = "CarRacing-v2"

In [44]:
env = gym.make(environment_name)

In [45]:
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 {})

In [46]:
env.observation_space

Box(0, 255, (96, 96, 3), uint8)

In [47]:
env.render()

In [49]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, truncated, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Episode:1 Score:-371.699999999994
Episode:2 Score:-861.4319148937219
Episode:3 Score:-862.1799227800276
Episode:4 Score:-888.2333333334443
Episode:5 Score:-879.1821917809309


In [50]:
env.close()

In [51]:
env.action_space.sample()

array([0.5030021 , 0.7945694 , 0.51055056], dtype=float32)

In [52]:
env.observation_space.sample()

array([[[ 95,  12,  13],
        [ 14, 253, 242],
        [111, 111, 226],
        ...,
        [154, 119, 234],
        [ 66, 202,  17],
        [207, 150, 191]],

       [[207,  58, 163],
        [208,  58,  30],
        [210, 108, 199],
        ...,
        [ 77,  54,   7],
        [205, 196,  75],
        [169,  40, 108]],

       [[ 43, 247, 123],
        [ 93, 168, 248],
        [184, 194, 167],
        ...,
        [154,  60, 121],
        [ 64, 241, 142],
        [ 32,  79,   7]],

       ...,

       [[ 50, 241, 114],
        [ 94, 249, 135],
        [ 38, 160, 216],
        ...,
        [172, 160,  39],
        [111, 100, 209],
        [ 15, 132, 245]],

       [[251,  59, 234],
        [179, 153, 199],
        [ 92, 149,  63],
        ...,
        [ 54, 145, 248],
        [110, 189,  25],
        [ 92, 217, 128]],

       [[229, 152,  79],
        [206,  48,  52],
        [  7, 199,  55],
        ...,
        [165,  82,  16],
        [142, 127, 121],
        [216,  57,  18]]

# 3. Train Model

In [23]:
log_path = os.path.join('Training', 'Logs')

In [24]:
model = PPO("CnnPolicy", env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


C:\Users\Nima\anaconda3\envs\tensorflow_python_3_10\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


RuntimeError: Calling torch.geqrf on a CPU tensor requires compiling PyTorch with LAPACK. Please use PyTorch built with LAPACK support.

In [25]:
model.learn(total_timesteps=40000)

NameError: name 'model' is not defined

# 4. Save Model 

In [ ]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_Driving_model')

In [ ]:
model.save(ppo_path)

# 5. Evaluate and Test

In [ ]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

In [ ]:
env.close()

In [ ]:
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

In [ ]:
env.close()